---
all:
    children:
        staging:
            hosts:
                hetzner-staging:
                    DEPLOY_USER: pialab
                    ansible_host: 65.21.243.33

            vars: # group variables
                DOMAIN_NAME: pialab.lesoctetslibres.com
                ansible_user: root
                backup_cron:
                    hour: 2
                    minute: 46

    vars:
        ansible_python_interpreter: /usr/bin/python3
