---
all:
    children:
        staging:
            hosts:
                hetzner-staging:
                    DEPLOY_USER: pialab
                    ansible_host: 65.21.243.33

            vars: # group variables
                DOMAIN_NAME: pialab.lesoctetslibres.com
                ansible_user: "{{ DEPLOY_USER }}"
                backup_cron:
                    hour: 2
                    minute: 46

    vars:
        ansible_python_interpreter: /usr/bin/python3
        ssh_user: "{{ DEPLOY_USER }}"
        ssh_disable_root_login: false
        ssh_identity_key: ~/.ssh/id_rsa.pub
