version: "3"

services:
  back:
    build: back
    container_name: pialab_back
    depends_on:
      - nginx-proxy
    volumes:
      - ./back/src:/var/www/pialab-back/
    ports:
      - '8000:80'
    environment:
      VIRTUAL_HOST: back.pialab.localhost # Managed by nginx-proxy
      VIRTUAL_PORT: 80

  front:
    build: front
    container_name: pialab_front
    depends_on:
      - back
      - nginx-proxy
    volumes:
      - ./front/src:/var/www/pialab-front/
    ports:
      - '8080:4200'
    environment:
      VIRTUAL_HOST: front.pialab.localhost # Managed by nginx-proxy
      VIRTUAL_PORT: 4200

  nginx-proxy: # Development only : allow tu use VIRTUAL_HOST environment variables
    image: jwilder/nginx-proxy
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
      # - "./docker/proxy-nginx.conf:/etc/nginx/cond.d/proxy.conf"
    ports:
      - "80:80"
    logging:
      driver: 'none' # Disable logging of this container
