
- name: update apt once a day
  apt: update_cache=yes cache_valid_time=86400 force_apt_get=true

- name: upgrade packages
  apt: upgrade=dist force_apt_get=true

- name: Installing required packages
  apt:
    state: present
    pkg:
      - git
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      - python-setuptools
      - python3-pip
      - vim
      - rsync

- name: add apt key for Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88

- name: Add APT repository for Docker.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
    state: present
  register: docker_repo

- name: Update apt cache if repo was added.
  apt: update_cache=yes
  when: docker_repo.changed

- name: installing docker packages
  apt:
    state: present
    pkg:
      - docker-ce
      - docker-ce-cli
      - containerd.io
  when: not FAST_DEPLOYMENT

- name: ensure docker-compose is not installed with apt
  apt:
    state: absent
    pkg:
      - docker-compose
  when: not FAST_DEPLOYMENT

- name: installing python docker packages
  pip:
    state: present
    name:
      - docker
      - docker-compose
  when: not FAST_DEPLOYMENT

- name: add deployment user to docker group
  ansible.builtin.user:
    name: "{{ DEPLOY_USER }}"
    groups: docker
    append: yes
 